# Generated by Django 4.2.1 on 2023-12-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='companyname',
            new_name='company_name',
        ),
    ]
